#
# BTstack example 'hid_keyboard_demo' for ESP32 port
#
# Generated by C:/msys32/home/minatsu/esp/btstack/port/esp32
# On 09/02/17 23:52:25

PROJECT_NAME := esp32_remote_shutter
EXTRA_COMPONENT_DIRS := components

include $(IDF_PATH)/make/project.mk
